name: feature
on:
  push:
    branches:
      - "feat/**"
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - run: echo "test..."
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - run: echo "build..."
  push:
    name: push
    runs-on: ubuntu-latest
    steps:
      - run: echo "push..."