name: pull-request
on:
  push:
    branches:
      - "feat(*)/**"

jobs:
    create-pull-request:
      runs-on: ubuntu-latest
      steps:
        - name: Check out repository code
          uses: actions/checkout@v2

        # pull request title will be used as the squash merge commit
        # branch names cannot contain colons(:), use forward slash as separator
        # branch name format:  <type>(<scope>)/<short summary>
        # semantic releasse format: <type>(<scope>): <short summary>
        - name: translate branch name format to semantic-release format for pull request
          id: semantic_release_name
          shell: bash
          run: |
            OUTPUT=$(echo "${{ github.ref_name }}" | sed 's|/|\: |' )
            echo "value=$OUTPUT" >> $GITHUB_OUTPUT

        - name: create pull request
          run: |
            gh pr create -B main \
              -H '${{ github.ref_name }}' \
              --title '${{ steps.semantic_release_name.outputs.value}}' \
              --body 'Pull ${{ steps.semantic_release_name.outputs.value}} into main\nAuto-created by a Github Action' || true
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}