name: release
on:
  push:
    branches:
      - master
      - main
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - run: echo "test..."
  release:
    name: release
    runs-on: ubuntu-latest
    needs: test
    steps:
      - run: env
      - uses: actions/checkout@v3
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.SEMANTIC_RELEASE_BOT_NPM_TOKEN }}