name: semantic-pr-validation
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  main:
    name: validate pr title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            fix
            feat
            docs
            style
            refactor
            perf
            test
            build
            ci
            chore
          scopes: |
            api
            db
          requireScope: true
          disallowScopes: |
            release
